create-ova: add option for a signing script

diff --git a/docker/scripts/build-ovf b/docker/scripts/build-ovf
--- a/docker/scripts/build-ovf
+++ b/docker/scripts/build-ovf
@@ -60,16 +60,20 @@ build_ovf() {
         params+=("$p")
     done
 
-    ovf_args="--ovf --mf --vmdk"
+
+    create_ova_args=("--ovf" "--mf" "--vmdk")
     if [ "${CREATE_OVA}" == "true" ] ; then
-        ovf_args=""
+        create_ova_args=()
+    fi
+    if [ -n "${SIGN_SCRIPT}" ] ; then
+        create_ova_args+=("--sign-script" "${SIGN_SCRIPT}")
+    fi
+    if [ -n "${OVA_NAME}" ] ; then
+        create_ova_args+=("--ova-name" "${OVA_NAME}")
     fi
 
-    ova_name=
-    [ -z "${OVA_NAME}" ] || ova_name="--ova-name=${OVA_NAME}"
-
     echo "running 'create-ova'"
-    printf "%s\0" "${params[@]}" | xargs -t -0 \
+    printf "%s\0" "${params[@]}" "${create_ova_args[@]}" | xargs -t -0 \
         docker run --rm \
         -v $(pwd):/workdir \
         --network=none \
@@ -77,10 +81,8 @@ build_ovf() {
         -e VMDKCONVERT_NUM_THREADS=${VMDKCONVERT_NUM_THREADS} \
         ${POI_IMAGE} \
         create-ova \
-            ${ovf_args} \
             --installer-config ${KS_CFG_FILE} \
-            --ova-config ${OVA_CFG_FILE} \
-            ${ova_name} || fail "'create-ova' failed with $?"
+            --ova-config ${OVA_CFG_FILE} || fail "'create-ova' failed with $?"
     echo "done with 'create-ova'"
 }
 
@@ -100,7 +102,7 @@ usage() {
     echo "          [--volume src:dst] additional volumes to be mounted to the docker container"
 }
 
-OPTS=$(getopt -o hc:v: --long ks-config:,compression-level:,num-threads:,ova,ova-config:,ks-param:,ova-param:,param:,ova-name:,poi-image:,releasever:,step:,volume: -n $0 -- "$@")
+OPTS=$(getopt -o hc:v: --long ks-config:,compression-level:,num-threads:,ova,ova-config:,ks-param:,ova-param:,param:,ova-name:,poi-image:,releasever:,step:,volume:,sign-script: -n $0 -- "$@")
 if [ $? != 0 ] ; then
     usage
     echo "Terminating." >&2
@@ -121,6 +123,7 @@ while true; do
         --ova-name)          OVA_NAME=${2} ; shift 2 ;;
         --ova-param)         OVA_PARAMS+=("${2}"); shift 2 ;;
         --poi-image)         POI_IMAGE=${2} ; shift 2 ;;
+        --sign-script)       SIGN_SCRIPT=${2} ; shift 2 ;;
         --step)              STEPS+=("${2}"); shift 2 ;;
         -v | --releasever)   RELEASE_VER=${2} ; shift 2 ;;
         --param)             COMMON_PARAMS+=("${2}"); shift 2 ;;
